# Generated by Django 5.0.2 on 2024-02-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Назва товару')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Ціна товару')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='Зображення товару ')),
                ('article', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
            ],
            options={
                'verbose_name': 'Виріб',
                'verbose_name_plural': 'Вироби',
            },
        ),
    ]
