# Generated by Django 5.0.2 on 2024-02-16 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_category_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='producer',
            new_name='category',
        ),
    ]
