# Generated by Django 5.0.2 on 2024-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_description_subcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Загловок сторінки')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Назва для ЧПУ')),
                ('content', models.TextField(blank=True, null=True, verbose_name='ОСновна інформація')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
            },
        ),
    ]
