# Generated by Django 5.0.2 on 2024-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Оcновна інформація'),
        ),
    ]
