# Generated by Django 5.0.2 on 2024-03-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_seo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Опис для SEO'),
        ),
        migrations.AddField(
            model_name='category',
            name='keywords_seo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключові слова для SEO'),
        ),
        migrations.AddField(
            model_name='page',
            name='description_seo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Опис для SEO'),
        ),
        migrations.AddField(
            model_name='page',
            name='keywords_seo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключові слова для SEO'),
        ),
    ]
