# Generated by Django 5.0.2 on 2024-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_article_alter_product_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='Зображення для підрозділу '),
        ),
    ]
