# Generated by Django 5.0.2 on 2024-07-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description_seo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Опис для SEO'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='keywords_seo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключові слова для SEO'),
        ),
    ]
