version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      container_name: ceramica_site_deploy
      command: gunicorn ceramica.wsgi:application --bind 0.0.0.0:8000

    env_file:
      - docker/prod/.env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3  # bind-mount для збереження БД між перезапусками
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: