version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    env_file:
      - docker/prod/.env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ceramica_db
      POSTGRES_USER: ceramica_user
      POSTGRES_PASSWORD: strong_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data:
